[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
target-version = "py310"
select = ["E","F","I","UP","B","SIM","PL"]
ignore = ["E501"]
fix = true

[tool.ruff.isort]
known-first-party = ["hydro","db","weather"]